`define OP_INVALID 4'h0
`define OP_LW 4'h1
`define OP_SW 4'h2
`define OP_OR 4'h3
`define OP_ADD 4'h4
`define OP_BEQ 4'h5
`define OP_LUI 4'h6
`define OP_ANDI 4'h7
`define OP_ADDI 4'h8
`define OP_LB 4'h9
